ostroproject/meta-ostro

doc/architecture/application-framework.rst, doc/architecture/architecture.rst, doc/architecture/efi-boot.rst, doc/architecture/security-threat-analysis.rst, doc/architecture/software-update.rst, doc/architecture/system-and-security-architecture.rst, doc/howtos/software-update-server.rst, doc/quick_start/access-support.rst, doc/sphinx_build/conf.py
Cleaned up TODO items
Changed Jira references to use GitHub issues
some more formatting issues fixed
security-threat-analysis: (from Teri Oda)
- clarifying that debug modes
could be used as an additional attack vector if not disabled in
final products and adding debug to the out-of-scope section.
- Added bluetooth explicitly to attack surfaces
conf.py
- removed references to old jira in substition macro (not used yet)
=> DOC: more review edits

doc/howtos/howtos.rst, doc/howtos/modifying-ostro-kernel.rst
provided by Geoffroy:
Add a How-To document on how to modify (code and config) the Ostro
kernel. More work is needed to add a section that talks about how
to integrate the changes in the source code tree (via an additional
layer and/or bbappend files).
[skip ci]
=> DOC: add modifying-ostro-kernel documentation

doc/howtos/booting-and-installation.rst
- Add instructions for running Ostro OS images on the
Intel Galileo Gen 2 platform
- Update image file format (now compressed with xz) and adjust instructions
accordingly
[skip ci]
=> booting-and-installation.rst: add Galileo instructions and minor updates

doc/quick_start/platforms.rst
The project now officially supports the MinnowBoard Turbot, a
MinnowBoard MAX compatible board. This patch updates the list of
supported platforms accordingly
[skip ci]
=> platforms.rst: update from MinnowBoard MAX to Turbot

meta-ostro/recipes-swupd/clr-systemd-config/clr-systemd-config_98.bb
"files://" is not the right method for finding the
license file. Correct is "file://".
"files://" no longer works with recent OE-core/bitbake, leading to:
ERROR: ExpansionError during parsing ..../clr-systemd-config_98.bb: Failure expanding variable do_fetch[file-checksums], expression was ${@bb.fetch.get_checksum_file_list(d)}  ${@get_lic_checksum_file_list(d)} which triggered exception IndexError: string index out of range
=> clr-systemd-config_98.bb: fix broken LIC_FILES_CHKSUM

doc/architecture/system-and-security-architecture.rst
=> system-and-security-architecture.rst: fix Ostro image names

doc/howtos/booting-and-installation.rst
Clarified you should write image to the whole SD card device (of=/dev/mmcblk0) and not
to just a partition (of=/dev/mmcblk0p1) - user feedback
[skip ci]
=> DOC: clarify dd command in booting-and-installation doc

doc/README.rst
Add more detailed instructions on how to generate the HTML
documentation from the reStructuredText files
[skip ci]
=> doc/README.rst: add instructions to generate HTML documentation

doc/howtos/building-images.rst
=> building-images.rst: fix README.md pointer to the integrity layer

doc/howtos/building-images.rst
- Added information about enabling SSTATE_MIRRORS (and references to Yocto Project
documentation for details)
- Updated platform/build target mapping to include specific platforms
[skip ci]
=> DOC: add use of SSTATE_MIRRORS to building-images doc

meta-ostro/conf/distro/ostro.conf
BBMASK setting in meta-ostro was intentionally appeding
to BBMASK since meta-oic was incorrectly initializing/
using BBMASK.
meta-oic is now fixed to not set BBMASK anymore so meta-osto's
BBMASK can be set to a sane value.
=> ostro.conf: update BBMASK

meta-ostro/conf/distro/ostro.conf
oe-core/meta-intel recently moved to 4.4 on all MACHINEs we are using.
However, some of the Ostro patches that are applied via linux-yocto_%.bbappend
in meta-ostro-bsp are not (yet) compatible with 4.4. The build fails with
MACHINEs we have not properly set PREFERRED_VERSION to 4.1 for linux-yocto.
Make sure all MACHINEs set PREFERRED_VERSION to 4.1 until we are
ready to move to 4.4.
=> ostro.conf: set linux-yocto preferred version to 4.1

meta-ostro/conf/distro/ostro.conf
This recipe is needed by isafw plugins to produce xml reports.
=> Add python-lxml-native to whitelisted recipes

meta-ostro/recipes-swupd/swupd-client/files/efi_combo_updater.c
The patch fixes problem when a null pointer is treated as
a null terminated string in strlen().
Fixes: IOTOS-1372
=> efi_combo_updater: Fix segfault for for the case of MMC device

meta-ostro/recipes-swupd/packagegroups/packagegroup-swupd.bb, meta-ostro/recipes-swupd/swupd-client/files/0001-change-systemctl-path-to-Ostro-systemctl-path.patch, meta-ostro/recipes-swupd/swupd-client/files/0002-Fix-build-failure-on-Yocto.patch, meta-ostro/recipes-swupd/swupd-client/files/0003-Right-usage-of-AC_ARG_ENABLE-on-bzip2.patch, meta-ostro/recipes-swupd/swupd-client/files/0004-Tolerate-quotes-in-os-release-files.patch, meta-ostro/recipes-swupd/swupd-client/files/0005-Disable-boot-file-heuristics.patch, meta-ostro/recipes-swupd/swupd-client/files/0006-swupd-client-Add-existence-check-to-staging-target.patch, meta-ostro/recipes-swupd/swupd-client/files/0007-Backport-Use-rename-instead-of-tar-transform.patch, meta-ostro/recipes-swupd/swupd-client/files/0008-Add-compatibility-with-libarchive-s-bsdtar-command.patch, meta-ostro/recipes-swupd/swupd-client/swupd-client_5700.bb
Currently GNU tar can't be used when IMA is enabled because
upon extracting a file it first creates it with `mknodat()`,
sets its xattrs and only then tries to open for writing and
fails since IMA prevents it.
This patch adds patches to swupd making it compatible with
bsdtar and switches it to actually use bsdtar.
=> Switch swupd to use bsdtar instead of GNU tar

meta-ostro/conf/distro/include/ostro_security_flags.inc
This reverts commit 9324c2f725ebd382e094ffec26a2a05a2e50615b.
The commit was a temporary fix for a scenario, where builds on certain
compilers were failing. The proper fix for this has been merged, so
this can be reverted.
=> Revert "ostro_security_flags.inc: Disable -fstack-protector-strong for openjdk"

meta-ostro/recipes-image/images/ostro-image.bb
Cretes a FEATURE_PACKAGES that contains development tool for Soletta.
So far, It includes just the Soletta Dev-App tool.
The feature is for only development purposes. It needs to be included only
in dev images.
Signed-off-by: Bruno Bottazzini <bruno.bottazzini@intel.com>
Differences from V3:
As @mythi and @barbieri suggested. Remove the packagegroup, and in the future, when adding more tools, we can create one or decide to put them somewhere else.
Differences from V2:
As pointed by @kad and @mythi, we had a name conflict and the build was failing. 
Changed the name to be soletta-dev-tools instead of soletta-dev.
Differences from V1:
As @mythi suggested, it shouldn't be added in devkit and we should create a soletta-dev feature.
Since we would add more feature in the future I created a …
=> ostro-imabe.bb: creates FEATURE_PACKAGES soletta-tools V4

doc/architecture/system-and-security-architecture.rst, doc/howtos/howtos.rst
Having "TODO" in the documentation was called out as a release
blocker. Let's use this PR to discuss how we can handle that properly.
[skip ci]
=> system-and-security-architecture.rst: remove TODO keyword

doc/howtos/building-images.rst, meta-ostro/classes/image-dsk.bbclass, meta-ostro/lib/image-dsk.py, meta-ostro/recipes-image/images/ostro-image.bb
This is functionally equivalent to PR #19, but leverages conversion
chaining from OE-core to achieve the same functionality with less
code. This also allows us to use the more natural and user-friendly
dsk.xz (instead of dsk_xz) IMAGE_FSTYPE.
Other benefits:
- all other compression methods also work ("dsk.bz2 dsk.lz4 ...")
- dependencies on the native tools are only added if really
required
- RM_OLD_IMAGE works for image files
The code can also be made even simpler after enhancing OE-core further.
It is safe to merge this code, too, enhancing OE-core can be done so that
there are no conflicts with the changes in this PR. Both is demonstrated
by https://github.com/pohly/ostro-os/tree/image-compression
=> support xz and zip compressed images

meta-ostro/conf/distro/ostro.conf
python3-setuptools and python3-pip were PNBLACKLISTed due to errors detected by
oeqa.selftest.iotsstatetests.SStateTests tests for edison vs. intel-core2-32
machines.
python3-setuptools is now needed by the new version of python-gobject recipe so
we need it enabled.
It is possible to just remove the PNBLACKLIST since we have split edison to it's
own package architecture (i.e., not sharing anything with core2-32) AND we are
no longer building with MACHINE=intel-core2-32.
=> ostro.conf: re-enable python3-* recipes

meta-ostro/recipes-image/images/ostro-image.bb
Now that extended attributes are properly supported, drop swupd
variant which was disabling ima and smack.
Signed-off-by: Igor Stoppa <igor.stoppa@intel.com>
=> Drop swupd variant.

doc/quick_start/quick_start.rst
[skip ci]
Signed-off-by: Ulf Hofemeier <ulf.hofemeier@intel.com>
=> Fix minor typo in Quick Start documentation.

meta-ostro/conf/conf-notes.txt, meta-ostro/conf/local.conf.sample
- Remove instructions on how to build an image to be run on
QEMU as it is not supported (because of limitations in the
EFI implementation of QEMU)
- Add instructions how to build for BeagleBone and BeagleBone
Black boards.
[skip ci]
=> local.conf.sample: remove QEMU and add BeagleBone machines

doc/howtos/booting-and-installation.rst
Updated flashall.sh location and how to run it
- flashall.sh script is now in the *.toflash.tar.bz2 tarball
- post build 399 (M3), the script is specific to the image downloaded (ostro-image and ostro-image-dev)
but with build 399 it isn't so a "-i <imagename>" argument was added to let the user override the
default imagename (keep that documented for now)
[skip ci]
=> DOC: update flashing instructions for Edison board

meta-ostro/classes/image-dsk.bbclass
It is not uncommon in the IoT space to use 4GB media to host your
OS. 4GB usually means 4.000.000.000 bytes and hence translates
into a real useable size of 3814MB. Setting the size of the rootfs
partition to 3700MB gives us a little buffer and should work with
all 4GB storage media (USB, SD cards, etc.) out there.
=> image-dsk.class: modify rootfs partition size to fit on 4GB media

meta-ostro/recipes-image/images/ostro-image.bb
QA needs some package/app for some test cases just enabled in dev image,
so use qatests feature and remove qatests from IMAGE_FEATURES
=> ostro-image.bb : Add qatests feature only in dev image

meta-ostro/conf/distro/ostro.conf
Enable usage of uninative feature for native components.
This would allow to re-use same native components across
different Linux distributions.
Config file comes from OE-Core, thus we can be sure that
it always points to corresponding to our state of OE-Core
shim glibc version, and this version already tested and
used within Yocto Project.
=> ostro.conf: enable uninative

meta-ostro/conf/bblayers.conf.sample, meta-ostro/conf/layer.conf
The first commit avoids the "NOTE: Your conf/bblayers.conf file has
been automatically updated." that each developer gets when starting to
use ostro-os.
The second commit relies on some changes currently staged in OE-core
master-next. It is already safe to merge now. However, whether we
really bump LAYER_CONF_VERSION when adding the next layer (most
likely, meta-swupd) remains to be seen.
Right now, automatically rewriting our bblayers.conf fails, and the
resulting error messages is very confusing
(https://bugzilla.yoctoproject.org/show_bug.cgi?id=9291 filed) for
users (quoted below). That depends on whether it is less confusing
than the error a developer gets when continuing to use an out-dated
bblayer.conf.
ERROR: Error executing a python function in exec_python_func() autogenerated: …
=> bblayers.conf versioning

doc/howtos/howtos.rst, doc/howtos/ip-address-config.rst
howtos/ip-address-config.rst
describe how to use ConnMan to configure a static or dynanic IP addresses
for a WiFi or Ethernet connection
howtos/howtos.rst
added ip-address-config to list of technical notes
[skip ci]
=> DOC: Add HowTo for configuring IP address with ConnMan

meta-ostro/conf/distro/ostro.conf, meta-ostro/recipes-security/ecryptfs-utils/ecryptfs-utils_110.bb, meta-ostro/recipes-security/gsignond-plugin-oauth/gsignond-plugin-oauth_1.0.0.bb, meta-ostro/recipes-security/gsignond-plugin-sasl/gsignond-plugin-sasl_1.0.0.bb, meta-ostro/recipes-security/gsignond/gsignond_1.0.4.bb, meta-ostro/recipes-security/libgsasl/libgsasl/0001-configure.ac-add-missing-AM_PROG_AR.patch, meta-ostro/recipes-security/libgsasl/libgsasl_1.8.0.bb, meta-ostro/recipes-security/libgsignon-glib/libgsignon-glib_2.4.1.bb
Add recipes for gSSO framework, including daemon, client library and
plugins.
Also adds recipes for following dependency components:
ecryptfs-utils
libgsasl
Following new components are white-listed in ostro.conf:
pkcs11-helper
=> Add gSSO framework and related dependencies

meta-ostro/recipes-security/libgsignon-glib/libgsignon-glib_2.4.1.bb
In some cases, build of Python support becomes auto-enabled causing
build failure.
=> libgsignon-glib: explicitly disable Python support

meta-ostro/conf/layer.conf, meta-ostro/conf/local.conf.sample
Remove the Qemu configuration block as QEMU is not supported
with Ostro due to its EFI implementation limitations
=> local.conf.sample: remove Qemu configuration block

meta-ostro/conf/local.conf.sample
Add information about the OSTRO_EXTRA_IMAGE_FEATURES variable and
why it is recommended to use it instead of Yocto EXTRA_IMAGE_FEATURES
which would add features to the ostro-initramfs.
[skip ci]
=> local.conf.sample: add information about OSTRO_EXTRA_IMAGE_FEATURES

meta-ostro/recipes-swupd/swupd-daemon/swupd-daemon_0.0.1.bb
swupd-daemon provides a D-Bus system-bus service for accessing Clear
Linux swupd-client functionality over a D-Bus API.
=> Add recipe for swupd-daemon

meta-ostro/conf/distro/ostro.conf
Disable running fsck at boot. System clock is typically wrong at early
boot stage due to lack of RTC backup battery. This causes unnecessary
fixes being made due to filesystem metadata time stamps being in future.
Ostro images use journaling filesystem and thus running fsck at boot is
not necessary
=> ostro.conf: disable running fsck at boot time

meta-ostro/recipes-extended/ostro-6lowpan/files/ostro-6lowpan-start.sh, meta-ostro/recipes-extended/ostro-6lowpan/files/ostro-6lowpan-stop.sh, meta-ostro/recipes-extended/ostro-6lowpan/files/ostro-6lowpan.service, meta-ostro/recipes-extended/ostro-6lowpan/ostro-6lowpan.bb
In order to use the 802.15.4 radio boards, some commands are needed, add thme as systemd service:
systemctl enable ostro-6lowpan
systemctl start ostro-6lowpan
Signed-off-by: Yong Li <yong.b.li@intel.com>
=> add systemd service files to config 802.15.4 radio boards

meta-ostro/recipes-image/images/ostro-image.bb
Set FEATURE_PACKAGES_node-runtime-tools and pull the packages defined
by the package group packagegroup-nodejs-runtime-tools.bb into the -dev
images.
Signed-off-by: Sudarsana Nagineni <sudarsana.nagineni@intel.com>
=> ostro-image.bb: Set FEATURE_PACKAGES_nodejs-runtime-tools

doc/howtos/building-images.rst, meta-ostro/conf/local.conf.sample
Ostro Project CI produces uninative SSTATE cache which is
beneficial for most of users to speed-up builds.
Enable it by default in local.conf
=> local.conf.sample: enable SSTATE_MIRRORS by default

doc/howtos/building-images.rst
Update doc for building images with more clarity for how to clone sources and build
an image and (trying to) bringing doc up to date with build #411 details.  Might need
to re-address build targets as final changes are made.
[skip ci]
=> DOC: update building-images

meta-ostro/conf/distro/ostro.conf
Switch preferred kernel version to 4.4 for meta-intel BSP machines.
Reduces need for backport patches.
=> ostro.conf: switch preferred kernel version to 4.4

meta-ostro/recipes-image/images/ostro-image.bb
A recent change in bitbake now triggers "Taskhash mismatch" errors for
do_rootfs when building Ostro images locally. CI builds are not affected
because BUILD_ID is set differently.
Ignoring the BUILD_ID -> DATETIME dependency looks like the right
solution, because conceptually we want the new value to be used when
it gets used, but we do not want a change in it to trigger a rebuild.
=> ostro-image.bb: avoid task hash mismatch

meta-ostro/classes/image-dsk.bbclass
The lack of microcode updates in our initrd may be relevant for the
milestone release we work on this week.
The other commit happens to touch the same lines and is included
to avoid merge conflicts with the meta-swupd tree.
=> include microcode in initrd again

meta-ostro/conf/distro/include/ostroproject-ci.inc
New variable OSTROPROJECT_CI_TEST_RUNS allows
to configure which images and with which test suite
and test data would be tested after CI build completed.
Format is space separated list of tuples.
Each tuple is comma separated list of items:
- image name to test
- test suite archive for that image
- test data archive for testsuite
- MACHINE build target
Variable can be overriden for each individual MACHINE
=> ostroproject-ci: enabler for flexible automatic testing

meta-ostro/recipes-soletta/dev-app/soletta-dev-app_%.bbappend
dev-app's do_install copies everything from ${S}, including
patches/ directory that is created by bitbake.
patches/ includes symlinks to patches applied from SRC_URI. These
symlinks point to destinations that do not get included in
do_install.
ostro-sanity.bbclass checks for dangling symlinks in rootfs as to
ensure swupd-enabled images work correctly.
To fix the QA errors, remove patches/ before copying everything
from ${S}.
=> soletta-dev-app: fix dangling symlinks in rootfs

doc/architecture/system-and-security-architecture.rst, doc/howtos/booting-and-installation.rst, doc/howtos/building-images.rst
@dkinder @gvancuts please help review. This completes the integration
of meta-swupd as far as normal developers go. Documenting the usage of
swupd and swupd-based images is intentionally left out for now. I don't
have plans to add anything further about that.
This also replaces PR #98.
[skip ci]
=> doc: cover changes related to swupd image reorganization

doc/howtos/booting-and-installation.rst, doc/howtos/building-images.rst, meta-ostro/classes/ostro-image.bbclass, meta-ostro/conf/conf-notes.txt, meta-ostro/conf/distro/include/ostro-os-development.inc, meta-ostro/conf/distro/include/ostroproject-ci.inc, meta-ostro/conf/distro/ostro.conf, meta-ostro/conf/local.conf.sample, meta-ostro/recipes-image/images/ostro-image-noswupd.bb, meta-ostro/recipes-image/images/ostro-image-swupd.bb
Removes the extra "ostro-image-swupd-reference" image and the
"reference" bundle and instead moves the content into the base images
of both ostro-image-swupd and ostro-image-noswupd.
Because the doc changes would conflict with the changes in PR #100,
this PR here includes all of those commits, too. That way we can
merge PR #100 and then this one, or this one directly.
@barbieri I hope this addresses your review feedback from PR #95.
@olev @mikko @kad I expect this to speed up the builds a bit.
=> simplify image content and bundles

doc/architecture/system-and-security-architecture.rst
This is the revision of the document what we expect to release in the
next Ostro OS milestone.
Ismo and I also looked at
https://github.com/pohly/meta-ostro/blob/architecture-doc-cleanup/doc/architecture/security-threat-analysis.rst
and came to the conclusion that it is okay as it stands, i.e. no further changes are planned.
=> system-and-security-architecture.rst: update based on recent swupd integration

meta-ostro/lib/devtool/__init__.py, meta-ostro/lib/devtool/kconfig.py
Add a kernel-menuconfig subcommand (only accessible within the
extensible SDK) that first puts the kernel into the workspace if it
isn't already, and then launches "make menuconfig".
(This is being added on the Ostro side because we'll need to do some
significant refactoring before it could go into OE-Core).
Signed-off-by: Paul Eggleton <paul.eggleton@linux.intel.com>
=> devtool: add kernel-menuconfig subcommand

meta-ostro/recipes-swupd/swupd-client/swupd-client_%.bbappend
Set `security.SMACK64` label explicitly on `/var/lib/swupd` to
avoid transmuting underlying directories which may be
directories that are installed as part of bundles.
The reason why it's needed is that first a directory installed
with `swupd bundle-add` command gets created under `/var/lib/swupd`
and then it is moved to its designated place. If `/var/lib/swupd`
has SMACK's transmute flag set then all directories created below
inherit this flag which leads to mismatched hashes.
=> swupd-client: Fix setting unwanted SMACK attrs

meta-ostro/conf/distro/ostro.conf
The extensible SDK is now published in two separate directories:
sdk/ for the installer .sh and sdk-data for the update data.
Therefore, we need to update SDK_UPDATE_URL to correctly point to
sdk-data.
=> ostro.conf: update SDK_UPDATE_URL

meta-ostro/classes/ostro-image.bbclass
Rename packagegroup-node-runtime to packagegroup-nodejs-runtime to
be consistent with the name of nodejs-runtime-tools packagegroup.
[1] https://github.com/ostroproject/meta-iot-web/pull/7
[2] This
Signed-off-by: Sudarsana Nagineni <sudarsana.nagineni@intel.com>
=> Rename packagegroup node-runtime to nodejs-runtime

meta-ostro/classes/ostro-image.bbclass
Busybox login has various shortcomings compared to login from shadow,
which is what OE-core uses. Switching to Busybox was a side effect of
update-alternative re-ordering for swupd images and can be undone by
raising the shadow priority, which is also needed for other commands
when going stateless.
Fixes: IOTOS-1498
=> ostro-image.bbclass: prefer shadow (motd, passwd, /dev/tty)

meta-ostro/classes/ostro-image.bbclass, meta-ostro/conf/distro/include/ostro-os-production.inc, meta-ostro/conf/distro/ostro.conf, meta-ostro/recipes-core/systemd/systemd_%.bbappend
This commit adds an image feature called 'muted' that can be
used disable all consoles and login services (getty).
In addition, 'muted' modifies systemd journald's log level such that
only emergency logs are logged. This essentially disables all debug
logs.
This leaves kernel printk setting unchanged. That is a BSP setting
Ostro does not need to touch.
The primary use for 'muted' is an a production image. Therefore, it
is added as a default there.
=> ostro-os-production.inc: disable consoles/getty and mute logging

meta-ostro/classes/ostro-image.bbclass, meta-ostro/conf/distro/ostro.conf
The npm install used in the .bb is causing troubles in CI build
environment and it makes many pull request to fail due to network
issues.
Temporarily disable soletta-dev-app from the image to get integration
moving faster.
=> ostro-image.bbclass: temporarily disable soletta-dev-app

README.rst
Add layers that are now used by the Ostro Project but not yet
documented in the README.rst file (namely: meta-security-isafw
and meta-swupd). Also shuffle the order to match the order in
which these are listed in conf/combo-layer.conf.
[skip ci]
=> README.rst: add layers that are now used in the project

README.rst
Add an explicit reference to where to look for more information
about the exact URL, branch and revision used for each of the
component forming the combined ostro-os repository.
[skip ci]
=> README.rst: add more information regarding components

doc/architecture/system-and-security-architecture.rst, doc/howtos/authorized-keys.rst, doc/howtos/building-images.rst, doc/howtos/howtos.rst
Expose how to enable remote ssh access by adding a new howto doc
and referencing it in places that implied it existed
[skip ci]
=> DOC: Authorized Keys for remote ssh access

doc/architecture/system-and-security-architecture.rst, doc/howtos/authorized-keys.rst, doc/howtos/building-images.rst, doc/howtos/howtos.rst
Expose how to enable remote ssh access by adding a new howto doc
and referencing it in places that implied it existed.  Some problem
with previous PR to add these changes, so second try (rebased to master).
[skip ci]
=> DOC: add how to use authorized_keys for remote access

meta-ostro/classes/ostro-image.bbclass
This reverts commit 774953a0dec3e0227b243a14c16997ad82f1bef8.
We do not want debug options enabled unconditionally. In this case,
the debug option has not been needed for a while, so it is easier
to remove the feature entirely.
=> ostro-image.bbclass: revert "Ostro: Start shell on init failure."

meta-ostro/recipes-core/packagegroups/packagegroup-app-framework.bb
The actual declaration/definition of the app-framework packagegroup
was missing from commit 979819f1c854b3199cdc172115c9993f22984be0.
Add it now.
=> recipes-core/packagegroups: add missing app-framework packagegroup.

doc/index.rst
Fixes: IOTOS-1474
platforms.rst was listed twice in TOC menu
[skip ci]
=> DOC: duplicate platforms link in doc menu

meta-ostro/classes/systemd-sysusers.bbclass
systemd specifies that all users have sysusers will end up having
/sbin/login, which was missing from the helper class, leading to
unintentionally creating the users with /bin/sh instead.
@ipuustin that fixes the problem you found. Please review.
=> systemd-sysusers.bbclass: set login shell to /sbin/nologin

meta-ostro/conf/distro/ostro.conf
Poky switched to disabling static libraries in 2.1. Ostro OS should do
the same, see commit for the reasoning.
I have not actually tested the change. This will have to be done as
part of CI and QA testing.
=> ostro.conf: disable static libraries

doc/howtos/firewall-configuration.rst
Document the case where a service needs to be run with non-root permissions but the firewall commands within `ExecStartPre=` and `ExecStopPost=` options should be run as root.
=> doc: firewall configuration for services not run as root.

doc/index.rst, doc/quick_start/contributor-guide.rst
Tutorial on how to contribute patches/new features to the Ostro OS using 'Pull Requests'
from Github. The tutorial shall cover the high-level workflow and provide guidance on
good practice such as commit message formats, what to send upstream, etc. This
tutorial will be published on the main Ostro OS project website.
force pushed more updates to address comments 
[skip ci]
=> DOC: contributor guide

meta-ostro/conf/distro/ostro.conf
The error message thrown when attempting to build a component
that is not included in the Ostro OS whitelist is not very helpful.
This commit improves it a little by giving the reason why building
such component is skipped.
[skip ci]
=> ostro.conf: improve message for components not whitelisted

meta-ostro/conf/distro/ostro.conf
The SDK_INHERIT_BLACKLISTed classes used in CI (and mirrored SSTATE)
cause locked signature file check failures with eSDK installation.
Until the blacklisted classes are fixed, SSTATE checks need to be
run in self-tests.
=> ostro.conf: disable SSTATE locked sigs checks

meta-ostro/classes/ostro-image.bbclass, meta-ostro/classes/stateless.bbclass, meta-ostro/conf/distro/include/stateless.inc, meta-ostro/conf/distro/ostro.conf, meta-ostro/conf/layer.conf, meta-ostro/recipes-swupd/swupd-client/swupd-client_%.bbappend
/etc was already getting included in bundles (because meta-swupd patches and
reconfigures swupd-server), now we also enable that for the client. At the same
time we re-configure Ostro OS such that the only content in /etc in the rootfs
directories is read-only.
This is an intermediate step towards stateless. Image updates from
"some files in /etc" to "no files in /etc" should work, too, because
we'll simply stop putting files into /etc and then the swupd client
will remove them (assuming we keep "update /etc" enabled in the
client).
@rojkov @igor-stoppa please review.
Replaces https://github.com/ostroproject/ostro-os/pull/58
=> swupd: enable updating of /etc

meta-fixes/recipes-devtools/python/python-pygobject_%.bbappend
gnome-common is not really needed (the native counterpart
pulled invia gnomebase.bbclass is enough). We can make
Ostro OS simpler and easier to review by not building it.
=> python-pygobject: avoid gnome-common dependency

meta-ostro/conf/local.conf.sample
Remove the extra space between '#' and the start of lines that can
be uncommented to tweak one's conf/local.conf file. This makes the
whole document more consistent as it is already done that way throughout
most of it and it also makes for a better user experience as forgetting
to remove the extra space at the start of the line generates a bitbake
parsing error.
[skip ci]
=> local.conf.sample: remove extra space in lines that can be uncommented

doc/howtos/howtos.rst, doc/howtos/pull-request-guidelines.rst, doc/quick_start/contributor-guide.rst
They document current practices and expectations when creating and
merging pull requests in the Ostro project. Writing them down is
useful as reference when transferring responsibilities and might help
to make the review process more efficient (less need to explain things
during review).
=> doc: add pull request guidelines

meta-ostro/recipes-image/images/ostro-image-swupd.bb
meta-swupd was updated such that the API changed, causing
https://github.com/ostroproject/ostro-os/pull/60 to fail unless this
PR here gets merged into meta-ostro.
There's no big risk associated with it, but also no pressing need as
the updates of ostro-os are currently done manually and can exclude
meta-swupd.
=> ostro-image-swupd.bb: prepare for BUNDLE_FEATURES API change in meta-swupd

doc/howtos/building-images.rst
Two commits to improve the building-images.rst file. One that fixes a typo and fixes some minor reST formatting issues (mainly double semi-colon that appeared in the final rendering). The second commit improves somewhat the section explaining how to add additional packages to an Ostro image by covering both noswupd and swupd cases.
[skip ci]
=> building-images: improvements

doc/quick_start/contributor-guide.rst
Triggered by a discussion on IRC with @uhofemei about PR #159: the
difference between commit message and pull request description turned
out to be unclear, and our documentation was not helping.
@uhofemei: is this better?
@dbkinder: please review. This uses "::" and might conflict with PR #158.
=> contributor-guide.rst: explain commit message and pull request description

doc/howtos/authorized-keys.rst, doc/howtos/booting-and-installation.rst, doc/howtos/ip-address-config.rst, doc/howtos/modifying-ostro-kernel.rst, doc/howtos/software-update-server.rst, doc/quick_start/contributor-guide.rst
Scanned through all .rst files to change incorrect code block
ReST tag shorthand from ":::" to "::"  (settled on using "::" vs. ": ::" consistently)
and force pushed.
[skip ci]
=> DOC: Fix incorrect use of ::: for code blocks

doc/howtos/modifying-ostro-kernel.rst
bitbake ostro-image is no longer a valid target name, changed to ostro-image-noswupd
[skip ci]
=> DOC: fix error in modifying-ostro-kernel.rst

meta-ostro/conf/distro/ostro.conf
The variable BB_NUMBER_PARSE_THREADS set in CI in order to
limit the number of parse threads should not leak to the user's
environment since it may increase SDK installation time and
worsen runtime performance on capable systems.
Fixes: IOTOS-1548
=> ostro.conf: Blaclkist BB_NUMBER_PARSE_THREADS for SDK

meta-ostro/classes/buildhistory-extra.bbclass
iotivity has
git://github.com/01org/tinycbor.git;protocol=https;name=cbor;destsuffix=${S}/extlibs/tinycbor/tinycbor
as entry in its SRC_URI. When we allow S to be expanded, we end up
with paths that vary from build to build.
Besides causing churn in the build history, it also causes iotivity to
show up once per architecture in the patch summary.
=> buildhistory-extra.bbclass: record ${S} and friends literally in history

meta-ostro/recipes-devtools/bmap-tools/bmap-tools_3.2.bb
During discussion of including bmap-tools to OE-Core it was discovered
that bmap-tools install machine independent file in deploy directory,
but task is machine dependant. This patch fixes inconsistency.
Reference: https://bugzilla.yoctoproject.org/show_bug.cgi?id=9414
=> bmap-tools: fix deploy class usage for machine independent files

meta-ostro/classes/image-dsk.bbclass, meta-ostro/classes/ostro-image.bbclass, meta-ostro/conf/bblayers.conf.sample, meta-ostro/conf/distro/include/ostroproject-ci.inc, meta-ostro/conf/distro/ostro.conf, meta-ostro/recipes-core/makeself/makeself_2.2.0.bb, meta-ostro/recipes-core/vboxmanage/files/configure.patch, meta-ostro/recipes-core/vboxmanage/files/disable-guest-additions.patch, meta-ostro/recipes-core/vboxmanage/files/fix-linker-flags.patch, meta-ostro/recipes-core/vboxmanage/files/include-dir.patch, meta-ostro/recipes-core/vboxmanage/files/remove-x11.patch, meta-ostro/recipes-core/vboxmanage/files/xpidl-build-fixes.patch, meta-ostro/recipes-core/vboxmanage/vboxmanage-native_5.0.16.bb
Add virtualbox recipe and virtualbox appliance generation as additional image type. Virtualbox appliances are currently generated for intel-corei7-64 and intel-quark images.
This is, at this stage, primarily meant to trigger CI testing and gather feedback. In no particular order:
* Recipes for virtualbox and libidl (which is dependency for virtualbox) are currently placed under meta-ostro/recipes-core. I'm not sure if this is the correct place.
* The shell function that handles the appliance generation is in image-dsk.bbclass. I'm not sure if this is proper place for this either.
* There was discussion on mailing list, that using intel-quark as the 32-bit variant is likely a bad idea, as it is highly machine dependent. Perhaps machine independent 32 bit image should be used instead …
=> Virtualbox appliance generation

meta-ostro/fixes/meta-iot-web/recipes-web/iotivity-node/files/oc-payload.cc-fix-signed-unsigned-char-issues.patch, meta-ostro/fixes/meta-iot-web/recipes-web/iotivity-node/iotivity-node.bbappend
Started to fail in recent CI pull, exact reason unknown. The code
clearly isn't handling signed char correctly, hence the patch.
=> iotivity-node: fix signed/unsigned char compiler problems

doc/howtos/software-update-server.rst
Fix a couple of formatting issues in the document: a couple
of literal blocks that were unnecessarily enclosed in
double-backticks which made those visible in the final rendering
and switch to use asterisks for a bullet list.
[skip ci]
=> software-update-server.rst: fix some formatting issues

meta-ostro/classes/buildhistory-extra.bbclass
The buildhistory entry for #440 lacks, for example, the LICENSE
information in adwaita-icon-theme because the entire 'variables' file
was never written.
See https://ostroproject.org/jenkins/job/build_edison/1414/consoleFull and
ostro-os_master/2016-05-03_03-01-12-build-441/761672d39c4822e6c18bc7b78f32446c2a5d2eb6/intel-quark
@kad please review, I'd like to include this for the next master build today.
=> buildhistory-extra.bbclass: fix storing of extra info

meta-ostro/conf/distro/include/ostro_security_flags.inc
This is blocking the next OE-core update, see https://github.com/ostroproject/ostro-os/pull/89
@ereshetova please review
=> ostro_security_flags.inc: use SECURITY_STRINGFORMAT

meta-ostro/classes/image-dsk.bbclass
VirtualBox uses a directory under /tmp for ipc. This can cause issues
if user already has VirtualBox installed, as the directory may already
exist and may be owned by root. The directory is renamed to avoid any
name collisions.
The VirtualBox working directory is also deleted, as this gets published, which is not intended.
Finally VirtualBox NIC is configured to use bridged mode instead of the default NAT, as this makes connecting to the VM easier from the host machine.
=> VirtualBox appliance generation: Change nic mode, delete temporary files and rename conflicting directory

meta-ostro/conf/ostro-multilib.conf
This is a test PR.
Multilib build fails currently for ostro-image-swupd, as libgcc creates a symlink to the 32 bit glibc directory. As we use uclibc as the 32 bit library instead, this symlink is broken, and a sanity check fails during a swupd related task.
Suppress this symlink creation instead by removing 'lib32' from MULTILIB_VARIANTS-variable for libgcc, so that libgcc recipe does not realize we are using multilib feature.  
=> ostro-multilib.conf: Fix galileo build

meta-ostro-fixes/meta-fixes/recipes-connectivity/openssl/openssl_%.bbappend, meta-ostro/classes/ostro-image.bbclass, meta-ostro/recipes-image/images/ostro-image-swupd.bb
Adds ptest packages to ostro-image-swupd-dev, as discussed with QA.
@testkit please review
The SERIAL_CONSOLES fix is necessary to re-enable running of tests on
qemu. The dangling symlink was found while experimenting with dbg-pkgs
in addition to ptest-pkgs (unfortunately that makes the image content
too large).
Both get added here in this PR to save test cycles.
=> update image content and configuration

meta-ostro/fixes/meta-java/recipes-core/openjdk/openjdk-8_%.bbappend, meta-ostro/fixes/meta-java/recipes-core/openjdk/openjre-8_%.bbappend
readdir_r() recently got marked as deprecated, which causes builds
against OE-core master to fail. Work around it until meta-java
maintainers (notified) come up with something better.
This PR blocks further updates of OE-core in ostro-os (like
https://github.com/ostroproject/ostro-os/pull/100).
=> openjdk/jre-8: ignore warnings about deprecated functions

meta-ostro/classes/image-dsk.bbclass
When attempting to launch .ova that is set into bridged mode, it fails
with an error message. While quickly toggling the mode to nat and then
back to bridged fixes the issue, it still looks bad. As a short term
solution the interface is reverted back to NAT mode until I have time to
investigate what the root cause is.
=> image-dsk.bbclass: Revert back to old network interface mode

meta-ostro/conf/distro/ostro.conf
Building the eSDK indirectly builds gsignond and its plugins, which
fails when using latest libsoup from OE-core master:
../../git/src/gsignond-oauth-plugin.c: In function 'gsignond_oauth_plugin_init':
../../git/src/gsignond-oauth-plugin.c:540:5: error: 'soup_session_async_new_with_options' is deprecated: Use 'soup_session_new' instead [-Werror=deprecated-declarations]
This blocks https://github.com/ostroproject/ostro-os/pull/100, for example in 
https://ostroproject.org/jenkins/job/build_beaglebone/1613/console
@kad okay to merge without testing? Running a build test would not tell us
much when done with current ostro-os master.
[skip ci]
=> ostro.conf: exclude gsignond from world build

meta-ostro/fixes/meta-java/recipes-core/openjdk/openjdk-8_%.bbappend
A space is missing in the CFLAGS_append, which can cause issues with GCC
flags.
=> openjdk-8_%.bbappend: Add space in _append

meta-ostro/recipes-security/groupcheck-settings-default/groupcheck-settings-default_0.1.bb, meta-ostro/recipes-security/groupcheck/groupcheck_git.bb
Groupcheck is a drop-in polkit replacement for embedded systems. It only supports authentication by group membership. See https://github.com/ostroproject/groupcheck for details.
This PR adds groupcheck recipe and its default (empty) configuration. It also adds groupcheck to Ostro OS images.
=> Add groupcheck to Ostro OS.

meta-ostro/conf/distro/include/ostroproject-ci.inc, meta-ostro/recipes-image/images/ostro-image-minimal.bb, meta-ostro/recipes-image/images/ostro-image-noswupd.bb
The minimal image is already useful without GPLv3, although achieving that goal at the same time would be nice.
=> ostro images: introduce minimal image without GPLv3

meta-ostro/conf/distro/ostro.conf
Some of our components (iotivity, Edison kernel) do not compile with
gcc 6.1 yet. Until they do, we need to stay on gcc 5.3.
This commit was tested successfully with the latest upstream
components in https://github.com/ostroproject/ostro-os/pull/110
@kad: agreed to use this as a workaround for the time being? Bugs against
iotivity and the kernel are filed, see comment in ostro.conf.
=> stay on gcc 5.3

meta-ostro/recipes-extended/libiio/libiio_git.bb
Add a new recipe for libiio, applications can use it to access iio devices
Signed-off-by: Yong Li <yong.b.li@intel.com>
=> Package libiio

meta-ostro/conf/distro/include/ostro-supported-recipes.txt, meta-ostro/recipes-image/images/ostro-image-swupd.bb
Add 2 QA test bundles into dev image to cover verification of shared contents between bundles.
qa-bundle-a: contains 2 recipes, hello-bundle-a and hello-bundle-s(shared).
qa-bundle-b: contains 2 recipes, hello-bundle-b and hello-bundle-s(shared).
[Relates-to]: IOTOS-1290
Signed-off-by: yma11 <yan.ma@intel.com>
=> Software Update: add QA test Bundles into dev image

doc/howtos/booting-and-installation.rst, doc/howtos/building-images.rst
Issue #113 notes user tried using .dsk format and bmaptool
to bitbake an image and create a bootable USB stick for an
Intel Edison board.
This patch updates documentation to clarify
.dsk format and use of bmaptool is for EFI platforms only
and won't work for Intel Edison (or BeagleBone Black).
Also addressed some formatting errors and clarity edits.
[skip ci]
=> DOC: clarify .dsk and bmaptool use for EFI platforms only

meta-ostro/classes/buildhistory-extra.bbclass
Put into buildhistory full information about binary package and
original recipe.
=> buildhistory-extra: record full information of package

meta-ostro/classes/stateless.bbclass, meta-ostro/classes/supported-recipes.bbclass
The old "except Foo, ex" no longer works once bitbake migrates to
Python3.
This is required (but not sufficient) for solving the Python3-related
problems in https://github.com/ostroproject/ostro-os/pull/116
We also need some of the already pending meta-openembedded patches.
=> classes: Python3 compatibility

meta-ostro/conf/distro/include/ostro-supported-recipes.txt, meta-ostro/recipes-core/packagegroups/packagegroup-tools-interactive.bb
Internal review raised some concerns about the upstream maintenance of
these components. Because there are no hard requirements for them and
there are alternatives for interactive use (tar is better for archival
than zip, and atop can show similar information as iotop), the easiest
solution is to remove the components.
=> ostro os: remove questionable zip and iotop

meta-ostro/classes/image-dsk.bbclass, meta-ostro/classes/stateless.bbclass, meta-ostro/conf/distro/include/ostro-supported-recipes.txt, meta-ostro/conf/distro/ostro.conf, meta-ostro/recipes-core/packagegroups/packagegroup-java-jdk.bb
This fixes build issues and allows Python3 in the target images.
Blocks https://github.com/ostroproject/ostro-os/pull/116 but is safe to merge already now.
=> prepare for Python3 migration

meta-ostro/classes/image-dsk.bbclass
Using 'exit 0' prevents any following code from being run. This means
that the unnecessary .dsk file is not being deleted and that .bmap files
are not being generated.
=> image-dsk.bbclass: Replace 'exit 0' with 'return'

meta-ostro/conf/local.conf.sample
- Add full path to a building-images.rst reference in local.conf
- Add paragraph that provides an option to enable systemd-bootchart
and add some basic explanation on how to use it
[skip ci]
=> local.conf.sample: add option to enable systemd-bootchart

meta-ostro/classes/image-dsk.bbclass
This commit tweaks a couple of default settings when creating an
OVA appliance:
- Boot Order: change from the default {floppy,dvd,disk,net} to
{disk,none,none,none} as we never need to try booting from a
different medium
- Storage bus (SATA) portcount: by default 30 ports are created
which leads to additional and unnecessary boot time. Set the
portcount to 1 enables just one SATA controller
=> image-dsk.bclass: tune default settings of the OVA appliance

meta-ostro/classes/ostro-image.bbclass, meta-ostro/conf/distro/ostro.conf, meta-ostro/recipes-devtools/mraa/mraa_%.bbappend, meta-ostro/recipes-devtools/upm/upm_%.bbappend
Java is a fairly heavyweight package, and it is likely that at least
some users would like to disable it altogether. Currently both mraa and
upm unconditionally depend on Java, which means it will get included in
the image even if the java-jdk packagegroup is not included.
A new distro feature, java, is introduced to gate both the mraa\upm and
java package group dependencies, so that Java can be easily disabled.
=> java: Move java behind DISTRO_FEATURES feature

meta-ostro/classes/image-dsk.bbclass, meta-ostro/classes/ostro-image.bbclass, meta-ostro/lib/image-dsk.py
Since EFI blobs contain predefined PARTUUIDs of rootfs and
are signed we have to generate two different EFI blobs
with different PARTUUIDs. Otherwise the kernel installed
on the device will get confused about which partition to
use as rootfs in case the installation USB stick is still
inserted into the device.
=> Add support for OS installer

meta-ostro/classes/ostro-image.bbclass
The Java and Python binding packages of mraa and upm were not
installed before because nothing depended on them. The two runtimes
can't depend on them because it is uncertain whether these optional
features are wanted, and the core devkit cannot depend on them because
it is uncertain whether the runtimes are wanted.
At the image level we can decide that based on the IMAGE_FEATURES.
Fixes: IOTOS-1680
=> ostro-image.bbclass: install mraa/upm bindings

meta-ostro/classes/ostro-image.bbclass
valgrind makes (more?) sense as a debugging tool than a profiling tool
(which is where it appears in OE-core), so let's add it to the
"tools-debug" image feature.
=> ostro-image.bbclass: add valgrind to debugging tools

meta-ostro/conf/distro/include/ostroproject-ci.inc, meta-ostro/conf/local.conf.sample
Frequent disk cpace checks create massive amount of transactions
to single NFS server in CI environment, but CI servers disks
are not likely to get full in regular building, so lets avoid
DISKMON checks in CI builds.
=> meta-ostro: Don't enable disk monitoring via BB_DISKMON_DIRS in CI

meta-ostro/classes/image-dsk.bbclass
Explicitly add "installer" boot parameter to the kernel command line
used by installation media. This way there's no need to detect if
the media is a USB-stick and as such is supposed to run installer.
The initramfs installed onto the target device's internal
storage shall have the installer disabled always.
=> image-dsk.bbclass: add installer param to kernel cmdline

meta-ostro/lib/supportedrecipes.py
It's short and useful for getting a quick report without having to
analyze the build history.
=> supportedrecipes.py: include license information

meta-ostro/recipes-core/packagegroups/packagegroup-devkit.bb
This requires https://github.com/ostroproject/meta-intel-iot-middleware/pull/10 before mraa-utils works correctly.
=> packagegroup-devkit.bb: add mraa-utils to devkit packagegroup

meta-ostro/recipes-core/vboxmanage/vboxmanage-native_5.0.24.bb
In order to support gcc-5.4, update VirtualBox to latest version.
=> Update VirtualBox to latest version

meta-ostro/classes/ostro-version.bbclass, meta-ostro/conf/distro/include/ostroproject-ci.inc, meta-ostro/conf/distro/ostro.conf
Since eSDK uses an overriden form for OS_VERSION calculation,
but with wrong input, we'd better have a single definition
for OS_VERSION where we can check the input.
=> ostro-version.bbclass: introduce single OS_VERSION definition

meta-ostro/classes/ostro-version.bbclass
The initial ostro-version.bbclass reverted to the Python3-incompatible
expression where  / 100 results in a floating point string.
Found when trying the code with Python3,see https://ostroproject.org/jenkins/job/build-recipe-selftests/2561/console
=> ostro-version.bbclass: Python3-compatible OS_VERSION

meta-ostro/fixes/meta-intel/recipes-kernel/linux/linux-yocto_4.4.bbappend
Updating meta-intel breaks compilation for intel-quark.
To avoid that build breakage until
https://bugzilla.yoctoproject.org/show_bug.cgi?id=9961
gets sorted out we freeze the intel-quark
kernel at the previous version.
This is relevant to avoid build breakages together
with the update meta-intel, see https://github.com/ostroproject/ostro-os/pull/147
=> linux-yocto_4.4.bbappend: freeze intel-quark kernel

meta-ostro/classes/ostro-version.bbclass
Modify ostro_get_os_version to return the default value
based on current date/time always except one CI specific
use case.
=> ostro-version.bbclass: leave only one special case check

meta-ostro/conf/distro/include/ostro-supported-recipes.txt, meta-ostro/conf/distro/ostro.conf
@igor-stoppa: we need to start building in the CI system now to get
this into the snapshot today. Therefore I went ahead and prepared this
PR.
I discussed the upcoming "enforce signature check unless explicitly
disable" patch with @ereshetova and she agreed that it is okay to use
3.6.0 without that patch for now, as long as we add that patch as soon
as it is available.
=> ostro: switch to latest swupd 3.6.0

meta-ostro/classes/image-dsk.bbclass
If the kernel command line changes, the UEFI app must be rebuilt,
to reflect the change.
Signed-off-by: Igor Stoppa <igor.stoppa@intel.com>
=> The UEFI app depends on the kernel command line

meta-ostro/conf/layer.conf, meta-ostro/conf/local.conf.sample
I tested this mode locally before creating the PR. The PR itself
still needs to be verified (i.e. we need to look at the content
of the resulting images).
=> local.conf: disable packaging of source code

meta-ostro/recipes-image/images/files/ima_policy_ostro
@rojkov please confirm. For reference:
.../linux-yocto-4.4$ git grep TRACEFS_MAGIC
fs/tracefs/inode.c:     err  =  simple_fill_super(sb, TRACEFS_MAGIC, trace_files);
include/uapi/linux/magic.h:#define TRACEFS_MAGIC          0x74726163
=> ima_policy_ostro: enable tracefs access

meta-ostro/fixes/meta-oic/recipes-core/iotivity/iotivity_%.bbappend
openembedded-core now correctly reveals if the build system
LDFLAGS aren't used (see openembedded-core commit
a98a8180863ff45b477a1f8439ebcec21151d282).
iotivity is one of the components that does not obey LDFLAGS.
However, fixing it needs a lot of rework in iotivity's scons
scripts.
Temporarily skip "ldflags" for all PACKAGES.
=> fixes: iotivity: skip "ldflags" QA test

doc/quick_start/contributor-guide.rst
Replace references to JIRA with github issue tracker
[skip ci]
=> doc: remove references to JIRA

meta-ostro/recipes-security/iptables-settings-default/files/default-ip6tables.rules
Pythons unit test (test_nntplib.py) fails because firewall doesn't
allow ipv6 input to localhost. Adding a rule from iptables.rules to
ip6tables.rules fixes this.
Signed-off-by: Simo Kuusela <simo.kuusela@intel.com>
=> default-ip6tables.rules: Update ipv6 firewall rules

meta-ostro/fixes/meta-intel/recipes-kernel/linux/linux-yocto_4.4.bbappend
This workaround is not needed anymore and is preventing necessary kernel
updates for Quark.
=> Remove static kernel version for Quark

meta-ostro/lib/oeqa/selftest/iotsstatetests.py
The subprocess.PIPE as stdout returns byte stream and thus cannot be
used with str.join().
Convert the byte stream to str to avoid a TypeError with str.join():
"TypeError: sequence item 0: expected str instance, bytes found"
=> iotsstatetests.py: python3: convert stdout byte stream to str

meta-ostro/fixes/meta-oic/recipes-apps/iotivity-sensorboard/iotivity-sensorboard_%.bbappend, meta-ostro/fixes/meta-oic/recipes-apps/iotivity-simple-client/iotivity-simple-client_%.bbappend, meta-ostro/fixes/meta-oic/recipes-core/iotivity/iotivity_%.bbappend
openembedded-core now correctly reveals if the build system
LDFLAGS aren't used (see openembedded-core commit
a98a8180863ff45b477a1f8439ebcec21151d282).
iotivity sample apps do not obey LDFLAGS. However, fixing it needs
meta-oic changes and that takes long time.
Temporarily skip "ldflags" for iotivity sample apps.
=> fixes: iotivity apps: skip "ldflags" QA tes

meta-ostro/conf/distro/include/ostro-supported-recipes.txt
The new version of gnutls pulled in from OE-Core adds a
dependency to libunistring.
Add libunistring to the list of supported recipes to get builds
going.
Signed-off-by: Mikko Ylinen <mikko.ylinen@linux.intel.com>
=> supported-recipes: add libunistring
