ostroproject/meta-ostro

doc/architecture/application-framework.rst, doc/architecture/architecture.rst, doc/architecture/efi-boot.rst, doc/architecture/security-threat-analysis.rst, doc/architecture/software-update.rst, doc/howtos/booting-and-installation.rst, doc/howtos/building-images.rst, doc/howtos/doc-guidelines.rst, doc/howtos/uefi-secure-boot.rst, doc/quick_start/about.rst, doc/quick_start/platforms.rst, doc/quick_start/quick_start.rst
Fixed Ostro trademark usage issues
Fixed sphinx/ReST formatting issues
Fixed references to OIC -> OCF
Fixed broken links
=> DOC: incorporate site review comments

doc/howtos/modifying-ostro-kernel.rst
Fixed some odd formatting in previous version
=> DOC: fix modifying-ostro-kernel

doc/quick_start/quick_start.rst
Added a link to the release notes (on GitHub) in the getting started guide
[skip ci]
=> DOC: add reference to release notes

doc/howtos/building-images.rst
=> building-images.rst: fix a couple of mistakes in documentation

doc/howtos/booting-and-installation.rst
=> Make reference to a section an actual hyperlink

meta-ostro/README
[skip ci]
The README should be about "meta-ostro" layer.
=> README: "iot layer" -> "meta-ostro layer".

doc/architecture/disk-layout.rst
Add more explanations about the dsk format and how to customize it.
Also, fix typos and formatting.
Signed-off-by: Igor Stoppa <igor.stoppa@intel.com>
=> Enhancements to disk layout docs.

doc/howtos/building-images.rst, doc/quick_start/platforms.rst
- platforms.rst: add BeagleBone Black description to the list
- building-images.rst: add to table mapping platforms with MACHINE
[skip ci]
=> Add BeagleBone Black to our documentation

doc/hardware/sensors.rst
Add documents for supported sensor list on Minnowmax/Galileo/Edison
[skip ci]
Signed-off-by: Box Yang <box.yang@intel.com>
=> DOC: Add the supported sensor list .rst file

doc/howtos/booting-and-installation.rst
Instructions include how to prepare microSD card and installing
needed boot and system files (and where to find them).
[skip ci]
=> DOC: Add (updated) booting instructions for Beaglebone Black

meta-ostro/conf/distro/include/ostroproject-ci.inc, meta-ostro/recipes-image/images/ostro-image.bb
This set of commits adjusts default parameters that are used inside Ostro Project CI
Obsoletes PR #50
=> ostroproject-ci.inc: defaults to be used by CI

doc/howtos/building-images.rst, meta-ostro/conf/distro/ostro.conf, meta-ostro/conf/local.conf.sample, meta-ostro/recipes-devtools/rpm/rpm_5.%.bbappend
This PR adds various cleanups and documents RM_OLD_IMAGE usage.
@dbkinder please check a6abbe9
@brunobottazzini FYI: 577557a. Closes: #48
=> Various cleanups + document RM_OLD_IMAGE usage

doc/hardware/hardware.rst, doc/hardware/sensors.rst
Fixed spelling typos, and added note about MinnowBoard Turbot
[skip ci]
=> DOC: hardware docs edit

doc/architecture/disk-layout.rst
partition misspelled in last paragraph
[skip ci]
=> DOC: spelling fixes for disk layout

doc/howtos/booting-and-installation.rst, meta-ostro/classes/image-dsk.bbclass, meta-ostro/conf/distro/include/ostroproject-ci.inc, meta-ostro/lib/image-dsk.py, meta-ostro/recipes-devtools/bmap-tools/bmap-tools_3.2.bb
- Ability to generate image checksums using custom compression/conversion mechanisms.
- Ability to generate BMAP files for images.
=> Enable BMAP (block map) Tools usage in Ostro

meta-ostro/recipes-soletta/dev-app/files/0001-Add-firewall-rules-to-allow-access.patch, meta-ostro/recipes-soletta/dev-app/soletta-dev-app_%.bbappend
Signed-off-by: Bruno Bottazzini <bruno.bottazzini@intel.com>
=> soletta-dev-app: Add iptables rules to allow access

meta-ostro/classes/ostro-image.bbclass
Added a package group for app framework. The app framework package group is now unconditionally included in the image as requested by QA. Removed the old and now unused app-privileges package group that used to collectively pull in the cynara, security manager, and app framework. Also removed the image post-processing workaround for the security-manager sqlite DB.
=> ostro-image.bb: removed unused app-privileges and added app-framework package group.

meta-ostro/classes/ostro-sanity.bbclass, meta-ostro/conf/layer.conf
@uhofemei is this better? :-) Also note that PR #100 enhances building-images.rst such
that the need to choose the mode is mentioned more prominently.
=> enhance development/production error message

meta-ostro/conf/distro/include/ostro_security_flags.inc
Signed-off-by: Elena Reshetova <elena.reshetova@intel.com>
=> Improve Ostro's security flags

doc/architecture/software-update.rst, doc/architecture/system-and-security-architecture.rst, doc/howtos/ip-address-config.rst, doc/quick_start/access-support.rst
Fixed some spelling errors and some edits for clarity and formatting
[skip ci]
=> DOC: spelling and format fixes

meta-ostro/recipes-core/busybox/busybox_%.bbappend, meta-ostro/recipes-core/busybox/files/ostro.cfg
Replaces PR #113 and simplifies busybox even further.
Removal of "ar" and "netcat" is based on customer feedback.
=> busybox: disable components

meta-ostro/conf/distro/include/ostro_security_flags.inc
Signed-off-by: Elena Reshetova <elena.reshetova@intel.com>
=> ostro_security_flags.inc: Adding format string flags

doc/howtos/firewall-configuration.rst
=> firewall-configuration: add link to AppFW arch document

doc/index.rst, doc/quick_start/contributor-guide.rst, meta-ostro/conf/distro/ostro.conf
Re-submit PR #133 and PR #139 that caused problems with the combo-layer tool. I have included both @dbkinder 's PR #133 and mine (PR  #139) keeping the original authors.
[skip ci]
=> Re-submit PR133 and PR139

doc/howtos/howtos.rst, doc/howtos/software-update-server.rst
This is PR #146 rebased onto current master. I'm creating it because
David had some problems while wrangling with git.
@dbkinder please do a quick check whether I rebased correctlty and then we can merge it.
=> DOC: tech edit for software-update-server.rst

doc/howtos/building-images.rst
Added some some additional instructions on how developers can add a package
and custom layer to the Ostro OS build
Force-pushed to address more review comments
[skip ci]
=> DOC: augment building-image documentation with adding a package

doc/howtos/building-images.rst
small technical edit to building-images from @pohly 
[skip ci]
=> DOC: update adding packages review comment to building-images

meta-ostro/conf/local.conf.sample
[skip-ci]
Change-Id: Ie1e05c01416bd55fd8544f7ec1dfacf3fc5dd14f
=> Fix variable name in local.conf.sample

doc/howtos/booting-and-installation.rst, doc/howtos/building-images.rst, doc/quick_start/access-support.rst
Updated documentation to take account the new dsk.ova format.
Depends on https://github.com/ostroproject/meta-ostro/pull/82
[ci skip]
=> Documentation: Documentation update for Virtualbox appliance generation

meta-ostro/conf/bblayers.conf.sample, meta-ostro/conf/distro/ostro.conf, meta-ostro/conf/layer.conf
Bumping release number and bblayer.conf version.
=> various distro meta data maintenance

meta-ostro/recipes-connectivity/avahi/avahi_%.bbappend, meta-ostro/recipes-connectivity/avahi/files/avahi-ipv4.conf, meta-ostro/recipes-connectivity/avahi/files/avahi-ipv6.conf
1. remove libnss-mdns dependency
2. enable `libdns_sd` support
3. add firewall support
=> avahi: enablers for adding avahi

meta-ostro/classes/supported-recipes.bbclass
Major new change is a report which also includes information about
source(s), home page and summary.
=> supported recipes: some enhancements

doc/howtos/booting-and-installation.rst
This section shows how to deploy an Ostro OS image
to the internal storage that might be available on certain
platforms.
Signed-off-by: Igor Stoppa <igor.stoppa@intel.com>
[skip-ci]
=> Documentation for deploying to internal storage.

doc/howtos/building-images.rst, doc/howtos/software-update-server.rst
- building-images.rst: fix bullet list rendering issue
- software-update-server.rst: fix a few typos and use '*'
for bullet list (to be consistent with other documents)
[skip ci]
=> doc: fix minor rendering issues in two documents

meta-ostro/conf/layer.conf, meta-ostro/conf/local.conf.sample
Support using the files in derived distros better (versioning, cleaner
local.conf.sample with no redundant spaces), more reliable sample
file location tracking.
=> conf file updates

doc/howtos/booting-and-installation.rst
=> booting-and-installation.rst: improve HTML rendering in a few places

doc/howtos/pull-request-guidelines.rst
Ostro OS needs to be secure by default and code review needs to ensure
that.
=> pull-request-guidelines.rst: explicitly mention backdoor and debug policy

meta-ostro/classes/ostro-image.bbclass
Signed-off-by: Brendan Le Foll <brendan.le.foll@intel.com>
=> ostro-image.bbclass: Add UPM & mraa nodejs & python bindings

meta-ostro/classes/image-dsk.bbclass
This should fix the race conditions that we have seen in some internal builds.
@igor-stoppa okay to merge once it has passed automated CI testing?
=> image-dsk.bbclass: deploy uefiapp into per-image directories

doc/howtos/app-dev-nodejs.rst, doc/howtos/howtos.rst
Add Sakari's application development using node.js document into the
howto tech note collection (IOTOS-344)
[skip ci]
Fixes: IOTOS-344
=> doc: add app dev using node.js tech note

meta-ostro/classes/image-dsk.bbclass, meta-ostro/lib/image-dsk.py
This fix is required for updating to OE-core master
(https://github.com/ostroproject/ostro-os/pull/116).
It was tested successfully in combination with OE-core master and some
other, related fixes in other repos
(https://github.com/ostroproject/ostro-os/pull/179), but should also
work with current OE-core master (will be tested as part of testing
this PR).
=> image-dsk: adapt to IMGDEPLOYDIR change

meta-ostro/classes/ostro-version.bbclass
OS_VERSION must not go backwards, which was not guaranteed when
deriving OS_VERSION from the BUILD_ID in pull request or component
master builds, because those builds have a different numbering than
the production builds for the ostro-os master.
Now we detect the kind of build and bump the OS_VERSION by 1000000000
in those non-master builds. Depends on support in the CI system for
CI_BUILD_TYPE.
=> ostro-version.bbclass: bump OS_VERSION by 1000000000 in non-master CI builds
